## Statische Grafiken mit `{ggplot2}`

### Karte f端r ein bestimmtes Jahr {.panelset}

#### Plot {-}

```{r map-2015}
source(here::here("utils/ggplot2_theme.R"), echo = FALSE)

mobile_world %>% 
  filter(year == 2015) %>% 
  ggplot(aes(fill = mobile_subs)) +
  geom_sf(colour = "#f8f8f8", size = .25) +
  scale_fill_continuous(limits = range(mobile_world$mobile_subs, na.rm = TRUE),
                        guide = guide_colourbar(label.position = "top",
                                                barwidth = 10, barheight = .5,
                                                ticks.linewidth = 1)) +
  coord_sf(label_axes = "----") +
  labs(fill = NULL,
       title = "Mobilfunkanschl端sse pro 100 Menschen",
       subtitle = "im Jahr 2015",
       caption = "Daten: OurWorldInData.org")
```

#### Code {-}

```{r ref.label='map-2015', echo=TRUE, eval=FALSE}
```

### Facetted-Grafik f端r mehrere Jahre {.panelset}

#### Plot {-}

```{r map-facets, fig.asp=.9, cache=TRUE}
mobile_world %>% 
  filter(year %in% 2000:2015) %>% 
  ggplot(aes(fill = mobile_subs)) +
  geom_sf(colour = "#f8f8f8", size = .25) +
  scale_fill_continuous(limits = range(mobile_world$mobile_subs, na.rm = TRUE),
                        guide = guide_colourbar(label.position = "top",
                                                barwidth = 10, barheight = .5,
                                                ticks.linewidth = 1)) +
  coord_sf(label_axes = "----") +
  facet_wrap(~year) +
  labs(fill = NULL,
       title = "Mobilfunkanschl端sse pro 100 Menschen",
       caption = "Daten: OurWorldInData.org")
```

#### Code {-}

```{r ref.label='map-facets', echo=TRUE, eval=FALSE}
```
